### ISSUE TITLE
rcs

### ISSUE THREAD

**Issue by Finguimbrine** [TORExitNode/csgo_selfleak#7]
there is n bug with rcs. have any idea in how to solve it?

**Comment by TORExitNode** [comment]
It's hard to help you when your not even describing the bug. How am I supposed to know whats wrong?

**Comment by Finguimbrine** [comment]
there is a bug when you change like ak to knife and go back, it goes up the ak

**Comment by Finguimbrine** [comment]
bad english

**Comment by Finguimbrine** [comment]
forget, going to fix it by myself
